### ISSUE TITLE
Getting back from whence one came

### ISSUE THREAD

**Issue by missulmer** [Senzing/evaluate#11]
**Is your feature request related to a problem? Please describe.**
I can't go back. 
Given the domain shift from Senzing.com via pathways from the product page and from developers, a user can't go back to their origin context with the back button.

**Describe the solution you'd like**
Please add top-level navigation "Products" to our page that links to "https://senzing.com/our-technology/"

**Describe alternatives you've considered**
We thought of offering a back button but because there is more than one user pathway that lands on this page from subpages within Senzing.com, we have set the "deploy now" button to spawn a tab and are now putting Products back in the top-level nav.

**Additional context**
As far as I understand, the only way to solve the 'back context break' is to migrate the evaluation page to the main sight framework and off gitpages.  Product isn't prioritizing that page migration for awhile. :)

**Comment by arawinters** [comment]
sort of.. there are what are referred to as "masked redirects", it kind of depends on how @antaenc set up the redirect though, or whether or not that's an option. not sure if it's a DNS or a CMS thing.
